### ISSUE TITLE
`qoaplay` returns garbage output on Windows 10

### ISSUE THREAD

**Issue by GithubPrankster** [phoboslab/qoa#1]
Compiling with `clang qoaplay.c -std=gnu99 -O3 -o qoaplay.exe`, playback of any `.qoa` file results a quick greeting of garbage output (thankfully I had followed the warning and set my headphones low!) and afterwards the player seemingly crashes. I also tried `zig cc` to similar effect.

I compiled `qoaconv` and thankfully it converts to and from `.qoa` normally.

**Comment by phoboslab** [comment]
The `b` flag for `fopen()` was missing. Linux makes no distinction for reading text/binary files, but Windows does.

Thanks for reporting!
