### ISSUE TITLE
qoa_test_samples doesn't match the code

### ISSUE THREAD

**Issue by pfusik** [phoboslab/qoa#12]
I'm testing my encoder and I noticed the sample archive doesn't match what the reference encoder produces:

    C:\0\ci\qoa\qoa>git status
    On branch master
    Your branch is up to date with 'origin/master'.

    nothing to commit, working tree clean

    C:\0\ci\qoa\qoa>git rev-parse HEAD
    2d74551f8c5b2cb8c94fe68959dbe1cf9977a793

    C:\0\ci\qoa\qoa>cc -O3 -o qoaconv.exe qoaconv.c

    C:\0\ci\qoa\qoa>cd ..\test

    C:\0\ci\qoa\test>unzip ../qoa_test_samples.zip bandcamp/allegaeon-beasts-and-worms.wav bandcamp/qoa/allegaeon-beasts-and-worms.qoa
    Archive:  ../qoa_test_samples.zip
      inflating: bandcamp/allegaeon-beasts-and-worms.wav
      inflating: bandcamp/qoa/allegaeon-beasts-and-worms.qoa

    C:\0\ci\qoa\test>..\qoa\qoaconv bandcamp/allegaeon-beasts-and-worms.wav allegaeon-beasts-and-worms.qoa
    bandcamp/allegaeon-beasts-and-worms.wav: channels: 2, samplerate: 44100 hz, samples per channel: 6712438, duration: 152 sec
    allegaeon-beasts-and-worms.qoa: size: 5295 kb (5422440 bytes) = 278.32 kbit/s, psnr: 39.44 db

    C:\0\ci\qoa\test>md5sum ../qoa_test_samples.zip bandcamp/allegaeon-beasts-and-worms.wav bandcamp/qoa/allegaeon-beasts-and-worms.qoa allegaeon-beasts-and-worms.qoa
    9b6ae38bb2980466c73b7453e638aa84 *../qoa_test_samples.zip
    98b16dfc3041f2d6384c1e378bee72aa *bandcamp/allegaeon-beasts-and-worms.wav
    50e5121fb63bc93553a963b9b221ac05 *bandcamp/qoa/allegaeon-beasts-and-worms.qoa
    5508a8f6194af9e046873e44a552674f *allegaeon-beasts-and-worms.qoa

    C:\0\ci\qoa\test>fc /b bandcamp\qoa\allegaeon-beasts-and-worms.qoa allegaeon-beasts-and-worms.qoa | head
    Comparing files BANDCAMP\QOA\allegaeon-beasts-and-worms.qoa and ALLEGAEON-BEASTS-AND-WORMS.QOA
    00275B00: F7 0F
    00275B01: DC F6
    00275B02: 50 DB
    00275B03: BB 7F
    00275B04: 0D B6
    00275B05: AD DF
    00275B06: 2D FD
    00275B07: C1 B7
    00275B10: C3 FF

**Comment by phoboslab** [comment]
I'm not entirely sure what I uploaded before, but the current archive is up to date now:
https://phoboslab.org/files/qoa-samples/qoa_test_samples_2023_02_16.zip

```
md5sum
5508a8f6194af9e046873e44a552674f  bandcamp/qoa/allegaeon-beasts-and-worms.qoa
6f97cb8a9363228df8bbf24971e70cd1  bandcamp/qoa_wav/allegaeon-beasts-and-worms.qoa.wav
```

Thanks for the notice!

**Comment by JohannesFriedrich** [comment]
Thanks for the updated files, @phoboslab !
Now my encoder works also on your files. Before I could just encode qoa files which were generated with qoaconv.c but not with your reference files.
