### ISSUE TITLE
Undefined behavior in the encoder: error * error overflows int

### ISSUE THREAD

**Issue by pfusik** [phoboslab/qoa#13]
The calculation `error * error` is performed using signed 32-bit arithmetic and it overflows for the `allegaeon-beasts-and-worms` test (probably many others as well).
The C and C++ standards only define unsigned arithmetic overflow while a signed overflow is an undefined behavior.

A possible fix is to change the variable to:

    long long error = (sample - reconstructed);

(wrapped with some typedef probably).
or perhaps check if `error` is in range `-sqrt(INT_MAX)..sqrt(INT_MAX)` - not sure if it's guaranteed that at least one scale factor will be in range.

**Comment by pfusik** [comment]
Note it's not only about standards compliance. Fixing it affects the encoding, for better I suppose.

**Comment by phoboslab** [comment]
Whoops! Thanks for the notice. I also updated all samples again: https://phoboslab.org/files/qoa-samples/qoa_test_samples_2023_02_18.zip

Funny enough I actually noticed the overflow in noise_shaping branch (https://github.com/phoboslab/qoa/blob/noise_shaping/qoa.h#L106) - it produced some _very_ audible artifacts. But I didn't notice it here.

**Comment by pfusik** [comment]
@JohannesFriedrich In #12 you mentioned your encoder. It's probably affected by this overflow.
