### ISSUE TITLE
Converted files have a "beep" at the beginning

### ISSUE THREAD

**Issue by mattdesl** [phoboslab/qoa#3]
Each file has a very loud noise at the beginning of the file once I convert from WAV to QOA and back to WAV.

Steps:
1. Cloned repo, commented out the `qoaplay` and MP3/FLAC bits in Makefile
2. Ran `make`
3. Run `./qoaconv input.wav input.qoa && ./qoaconv input.qoa output.wav`
4. `output.wav` has a noticeable beep, occurs on all tested WAV files

This loud part at the beginning should not be present in the output WAV:

<img width="393" alt="Screenshot 2023-02-02 at 6 33 22 pm" src="https://user-images.githubusercontent.com/1383811/216418732-a0a13b03-41e9-4a84-a746-cb8dc7ce71d2.png">

Using a MacBook Pro M1 Max, macOS 12.5.1.

**Comment by phoboslab** [comment]
Can you please provide the original WAV file, to see if I can reproduce it?

**Comment by phoboslab** [comment]
The above commit should fix this problem, I believe. Please let me know if it's still present.

Thanks for reporting!

**Comment by mattdesl** [comment]
Works now! Thanks. Great little library here, going to see if I can make a JS implementation.
