### ISSUE TITLE
Quantizing weights & history samples for the frame header causes audible clicks

### ISSUE THREAD

**Issue by phoboslab** [phoboslab/qoa#4]
[As pointed out on HN](https://news.ycombinator.com/item?id=34630543) there are some audible periodic clicks, particularly in the 24_tuba_arpegio_melodious_phrase_stereo test sample. As I have now confirmed, this is indeed happening because of the quantization of weights and history samples for the frame headers [here](https://github.com/phoboslab/qoa/blob/master/qoa.h#L324-L336).

Currently, the quantization is just `history[i] >> 8`. These clicks go away when quantizing with something that remains more accurate at the lower end (e.g. `sqrt(weights[i]`). However, I think the added complexity of having `sqrt` or some kind of `exponent + mantissa` representation that fits into 8 bits there is not worth it.

Or is there some simple way to quantize 16 bit ints into 8 bit with something that approximates `sqrt()`?

Anyway, my current plan is to just store the LMS state unquantized. That is: 16 bit for each weight and history sample. This increases the bitrate to 278kbits/s (44100hz, stereo). I would also change the layout of the frame header, so that the weights and history samples can be stored/loaded as 64bits each. So instead of:

```c
struct {
	struct {
		int8_t history;    // quantized to 8 bits
		int8_t weight;     // quantized to 8 bits
	} lms_entry[4];
} lms_state[num_channels]; 
```

we would have

```c
struct {
	int16_t history[4];
	int16_t weights[4];
} lms_state[num_channels]; 
```

Thoughts?

**Comment by kleinesfilmroellchen** [comment]
Sounds like a good approach to me, especially because it trivially un-nests the history and weight data.

As for better quantization: sqrt only seems to be a better solution because of integer math (for -1 <-> 1 floats `sqrt(x) ~= x`) but is not worth the added complexity in my opinion. I could not find a simple algorithm for square roots, at least not a non-iterative one. As said, the only approximation known to me only works for normalized rational sample representations.

**Comment by dumblob** [comment]
[lolremez](https://github.com/samhocevar/lolremez ) is **very good** at approximating with only a few multiplications.

**Comment by dumblob** [comment]
Btw. in [Nuklear](https://github.com/Immediate-Mode-UI/Nuklear/ ) we use inverse square root as its usage results in faster generated assembly.

**Comment by kleinesfilmroellchen** [comment]
> [lolremez](https://github.com/samhocevar/lolremez ) is **very good** at approximating with only a few multiplications.

But it requires floating-point math, which QOA explicitly avoids

**Comment by dumblob** [comment]
> But it requires floating-point math, which QOA explicitly avoids

It does not. lolremez generates C code with floating point data types but the principle works for integers too (with a small additional effort, of course).

**Comment by phoboslab** [comment]
I went ahead and did the obvious thing now.

lolremez looks amazing. I wish I had know about this earlier to different things on the residuals. For this case, the added complexity of yet another encoding scheme is certainly not worth saving 1kbit/s
