### ISSUE TITLE
qoa_read_u64 optimizations

### ISSUE THREAD

**Issue by nigeltao** [phoboslab/qoa#5]
https://godbolt.org/z/Ezd47sd5M suggests that the current [qoa_read_u64](https://github.com/phoboslab/qoa/blob/e9b81424e5a0c47ca6cf20e75729e5eeb8e4b8fe/qoa.h#L278) function produces a surprising amount of `x86_64` machine code. Certainly a lot more than "just a mov (and bswap)".

This is possibly because something like the `(*p)+5` in `(uint64_t)bytes[(*p)+5] << 16` can overflow an `unsigned int` (but an `unsigned int` is not a `size_t`). But I'm just guessing.

Since it's called pretty deep in the `qoa_decode_frame` loop, this `qoa_read_u64` function might be worth optimizing.

**Comment by phoboslab** [comment]
Thanks! That made the decoder slightly faster :)
